# Generated by Django 4.2.29 on 2026-03-26 00:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0013_add_run_count_to_signal_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalreport",
            name="suggested_reviewer_user_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
    ]
